### ISSUE TITLE
Installing via pip - no matching distribution

### ISSUE THREAD

**Issue by David-Rodden** [cerniglj1/OSRSQuestTool#1]
Unable to install via pip, `pip install osrsquesttool`, is there a naming issue?

**Comment by cerniglj1** [comment]
I've removed this as a pypi project and may revisit in the future. I'm sorry for the inconvenience, but you can still just copy past the json file located in this repo if you still want the data!

It's now a node package instead of a pypi package. Feel free to message me if there is anything I can do to help you.
